(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const render=()=>{const root=document.getElementById('grid');if(!root||!window.AbysssModel)return;const model=AbysssModel.load();root.replaceChildren(...model.timers.map((t,i)=>{const card=document.createElement('article');card.className='abyss-card';card.dataset.timerId=t.id;card.innerHTML=`<div class="abyss-card-head"><input class="abyss-name" data-timer-input data-timer-id="${esc(t.id)}" value="${esc(t.name||`深淵 ${i+1}`)}" aria-label="タイマー名"><button class="abyss-sync" type="button" data-sync="${esc(t.id)}" aria-label="このタイマーを同期">↻</button></div><div class="abyss-core"><div class="abyss-count"><span class="abyss-current">${t.current}</span><span class="abyss-slash">/</span><span class="abyss-max">${t.max}</span></div><div class="abyss-time">${t.running?'回復中':'待機中'}</div></div><div class="abyss-actions"><button type="button" data-action="consume40" data-id="${esc(t.id)}">40消費</button><button type="button" data-action="start" data-id="${esc(t.id)}">開始</button><button type="button" data-action="stop" data-id="${esc(t.id)}">停止</button></div>`;return card}));};
const syncCard=id=>{const model=AbysssModel.load(),i=model.timers.findIndex(t=>t.id===String(id));if(i<0)return;const before=model.timers[i],after=AbysssModel.recover(before);if(JSON.stringify(before)!==JSON.stringify(after)){model.timers[i]=after;AbysssModel.save(model)}render()};
document.addEventListener('pointerup',e=>{const sync=e.target.closest?.('[data-sync]');if(sync){e.preventDefault();syncCard(sync.dataset.sync);return}const action=e.target.closest?.('[data-action]');if(!action||!window.AbysssActions)return;const id=action.dataset.id;({consume40:AbysssActions.consume40,start:AbysssActions.start,stop:AbysssActions.stop}[action.dataset.action])?.(id)},{passive:false});
window.AbysssAbyssUI={render,syncCard};
window.addEventListener('abysss:modelchange',render);
})();
