(()=>{
'use strict';
const CAP=12*60*60*1000,LEAD=5*60*1000,STEP=5*60*1000;
const recover=t=>{const idleStart=Number(t.idleStart);return {...t,idleCapMs:Number(t.idleCapMs)||CAP,idleStart:Number.isFinite(idleStart)&&idleStart>0?idleStart:null,idleRunning:!!t.idleRunning}};
const info=t=>{const r=recover(t),start=Number(r.idleStart);if(!r.idleRunning||!Number.isFinite(start)||start<=0)return {elapsed:0,remaining:null,complete:false,armed:false,steps:0,claimable:0};const elapsed=Math.max(0,Date.now()-start),cap=Number(r.idleCapMs)||CAP,clamped=Math.min(elapsed,cap),steps=Math.floor(clamped/STEP),remaining=Math.max(0,cap-elapsed);return {elapsed,remaining,complete:remaining===0,armed:remaining<=LEAD,steps,claimable:steps}};
const start=id=>{const m=AbysssModel.load(),i=m.timers.findIndex(t=>t.id===String(id));if(i<0)return null;const t=recover(m.timers[i]);if(t.idleRunning)return t;const next={...t,idleStart:Date.now(),idleRunning:true,idleCapMs:Number(t.idleCapMs)||CAP};m.timers[i]=next;AbysssModel.save(m);window.dispatchEvent(new CustomEvent('abysss:modelchange'));return next};
const claim=id=>{const m=AbysssModel.load(),i=m.timers.findIndex(t=>t.id===String(id));if(i<0)return {reward:0,state:null};const t=recover(m.timers[i]),before=Number(t.idleClaimedSteps)||0,now=info(t),available=Math.max(0,now.steps-before);if(available<=0)return {reward:0,state:now};const next={...t,idleClaimedSteps:before+available};if(now.complete){next.idleRunning=false;next.idleStart=null;next.idleClaimedSteps=0}m.timers[i]=next;AbysssModel.save(m);window.dispatchEvent(new CustomEvent('abysss:modelchange'));return {reward:available,state:info(next)} };
const stop=id=>{const m=AbysssModel.load(),i=m.timers.findIndex(t=>t.id===String(id));if(i<0)return null;const next={...recover(m.timers[i]),idleRunning:false,idleStart:null,idleClaimedSteps:0};m.timers[i]=next;AbysssModel.save(m);window.dispatchEvent(new CustomEvent('abysss:modelchange'));return next};
window.AbysssIdle={CAP,LEAD,STEP,recover,info,start,claim,stop};
})();
